[package]
name = "los"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi_rgb = "0.2.0"
sbi-rt = { version = "0.0.3", features = ["legacy"] }

[profile.release]
opt-level = 0
debug = true
panic = "abort"

[[bin]]
name = "los"
test = false
bench = false
