[package]
name = "los"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi_rgb = "0.2.0"
pretty-hex = { version = "0.4.1", default-features = false }
sbi-rt = { version = "0.0.3", features = ["legacy"] }
